from dataclasses import dataclass, field
from threading import Lock
from typing import Any, Optional

from .api_navigation.create_path import get_google_route
from .api_navigation.decode_route import extract_route_points

from .navigation_tools.navigate import navigate
from .navigation_tools.movement import movement
from .navigation_tools.fnpp import (
    calculate_distance,
    to_tuple,
)

from .other_tools.frame_extraction import get_frame

from .self_navigation.distance_graph import juet_weighted_graph
from .self_navigation.polyline import (
    polyline_database,
    polypoints_db,
)


# ============================================================
# CONFIGURATION
# ============================================================

# Distance within which a destination is treated as reached.
# We are using the 7m threshold for mission arrival.
ARRIVAL_THRESHOLD = 3.5


# Safety command used whenever routing fails or state is invalid.
SAFE_STOP_COMMAND = "STOP"


# Supported routing modes
SELF_ROUTE = 1
GOOGLE_ROUTE = 0


# ============================================================
# PIPELINE STATE
# ============================================================

@dataclass
class PipelineState:
    """
    Runtime state of the current delivery mission.

    This currently represents ONE robot.
    Later, for fleet support, this state should become
    robot_id -> PipelineState.
    """

    active: bool = False

    # Unique identity of the current mission.
    mission_key: Optional[tuple] = None

    # Routing mode requested for the mission.
    routing_mode: Optional[int] = None

    # Actual routing source in use.
    # Examples:
    #   "self"
    #   "google"
    #   "self_fallback"
    routing_source: Optional[str] = None

    # Mission phase
    #
    # IDLE
    # TO_PICKUP
    # TO_DELIVERY
    # COMPLETE
    phase: str = "IDLE"

    # Route waypoint lists
    receive_points: list = field(default_factory=list)
    deliver_points: list = field(default_factory=list)

    # Persistent waypoint indexes
    receive_waypoint_index: int = 0
    deliver_waypoint_index: int = 0

    # Last command generated by pipeline
    last_command: str = SAFE_STOP_COMMAND

    # Last routing error
    last_error: Optional[str] = None


# One-robot prototype state
state = PipelineState()

# Lock protects state because FastAPI/background calls can be concurrent.
state_lock = Lock()


# ============================================================
# BASIC COORDINATE HELPERS
# ============================================================

def _coordinate_dict(coords):
    """
    Convert Pydantic/object/tuple/dict coordinates into
    the internal graph format:

        {
            "lats": latitude,
            "longs": longitude
        }

    Used by the JUET graph resolver.
    """

    latitude, longitude = to_tuple(coords)

    return {
        "lats": latitude,
        "longs": longitude
    }


def _mission_key(marketplace, delivery_point, routing_mode):
    """
    Build an identifier for the current mission.

    Kart coordinates are intentionally NOT included because
    kart coordinates change continuously during navigation.
    """

    marketplace_point = to_tuple(marketplace)
    delivery_point_value = to_tuple(delivery_point)

    return (
        round(marketplace_point[0], 7),
        round(marketplace_point[1], 7),
        round(delivery_point_value[0], 7),
        round(delivery_point_value[1], 7),
        int(routing_mode),
    )


# ============================================================
# OBSTACLE RESULT NORMALIZATION
# ============================================================

def _has_obstacle(obstacle_result):
    """
    Normalize obstacle detection result.

    Current movement.py returns:

        True / False

    But older code may return:

        "true" / "false"

    This helper safely supports both.
    """

    value = obstacle_result

    if isinstance(value, bool):
        return value

    if isinstance(value, str):
        return value.strip().lower() == "true"

    return bool(value)


def _normalize_command(command):
    """
    Normalize movement commands to the project's standard
    uppercase command format.
    """

    if command is None:
        return SAFE_STOP_COMMAND

    command = str(command).strip().upper()

    if not command:
        return SAFE_STOP_COMMAND

    return command


# ============================================================
# GOOGLE ROUTE
# ============================================================

def _get_google_points(origin, destination):
    """
    Fetch and decode a Google route.

    Returns:
        list of waypoint dictionaries

    Raises no exception outward; returns [] on failure.
    """

    try:

        route_response = get_google_route(
            origin,
            destination
        )

        if not route_response:
            return []

        points = extract_route_points(
            route_response
        )

        if not points:
            return []

        return points

    except Exception as error:

        state.last_error = (
            f"Google route error: {error}"
        )

        return []


# ============================================================
# SELF NAVIGATION — GRAPH SEARCH
# ============================================================

def _find_closest_vertex(coords):
    """
    Find the closest graph vertex to the given coordinates.

    We intentionally do not depend on the current
    close_coords.py implementation because that file
    currently has import/structure issues in the repository.

    Returns:
        vertex name or None
    """

    current_point = to_tuple(coords)

    closest_vertex = None
    shortest_distance = float("inf")

    for vertex, data in polypoints_db.items():

        try:

            vertex_point = (
                float(data["lats"]),
                float(data["longs"])
            )

        except (KeyError, TypeError, ValueError):
            continue

        distance = calculate_distance(
            current_point,
            vertex_point
        )

        if distance < shortest_distance:

            shortest_distance = distance
            closest_vertex = vertex

    return closest_vertex


# ============================================================
# SELF NAVIGATION — SHORTEST PATH
# ============================================================

def _find_shortest_graph_path(
    start_vertex,
    end_vertex
):
    """
    Find the shortest simple path in the current JUET graph.

    The current campus graph is small, so exhaustive DFS is
    acceptable for the prototype.

    Returns:
        tuple(path_vertices)

    Example:
        (
            "A",
            "A1",
            "A2",
            "A6",
            "X"
        )

        Returns None when no path exists.
    """

    if start_vertex is None or end_vertex is None:
        return None

    if start_vertex not in juet_weighted_graph:
        return None

    if end_vertex not in juet_weighted_graph:
        return None

    best_path = None
    best_distance = float("inf")

    def dfs(
        current_vertex,
        current_path,
        current_distance
    ):
        nonlocal best_path
        nonlocal best_distance

        # Target reached
        if current_vertex == end_vertex:

            if current_distance < best_distance:

                best_distance = current_distance
                best_path = tuple(current_path)

            return

        connections = juet_weighted_graph[
            current_vertex
        ].get(
            "connections",
            {}
        )

        for next_vertex, edge_distance in connections.items():

            # Avoid cycles
            if next_vertex in current_path:
                continue

            # Don't explore if already worse than known best path
            new_distance = (
                current_distance
                + float(edge_distance)
            )

            if new_distance >= best_distance:
                continue

            dfs(
                next_vertex,
                current_path + [next_vertex],
                new_distance
            )

    dfs(
        start_vertex,
        [start_vertex],
        0.0
    )

    return best_path


# ============================================================
# SELF NAVIGATION — EDGE POLYLINE RESOLUTION
# ============================================================

def _find_edge_polyline(
    start_vertex,
    end_vertex
):
    """
    Find the stored polyline between two connected graph
    vertices.

    The database may store:

        A-B

    or:

        B-A

    If reverse direction is used, the points are reversed.
    """

    forward_key = (
        f"{start_vertex}-{end_vertex}"
    )

    reverse_key = (
        f"{end_vertex}-{start_vertex}"
    )

    # --------------------------------------------------------
    # Forward edge
    # --------------------------------------------------------

    if forward_key in polyline_database:

        values = polyline_database[
            forward_key
        ]

        points = []

        for point in values.values():

            try:

                points.append({
                    "point": len(points) + 1,
                    "latitude": float(point["lats"]),
                    "longitude": float(point["longs"])
                })

            except (KeyError, TypeError, ValueError):
                continue

        return points

    # --------------------------------------------------------
    # Reverse edge
    # --------------------------------------------------------

    if reverse_key in polyline_database:

        values = polyline_database[
            reverse_key
        ]

        points = []

        for point in reversed(
            list(values.values())
        ):

            try:

                points.append({
                    "point": len(points) + 1,
                    "latitude": float(point["lats"]),
                    "longitude": float(point["longs"])
                })

            except (KeyError, TypeError, ValueError):
                continue

        return points

    return []


# ============================================================
# SELF NAVIGATION — PATH TO WAYPOINTS
# ============================================================

def _graph_path_to_points(path):
    """
    Convert a graph vertex path into a dense waypoint route
    using the stored campus polylines.

    Example:

        A → A1 → A2

    becomes the actual GPS points stored in:

        A-A1
        A1-A2
    """

    if not path:
        return []

    if len(path) == 1:

        vertex = path[0]

        point = polypoints_db.get(
            vertex
        )

        if not point:
            return []

        return [{
            "point": 1,
            "latitude": float(point["lats"]),
            "longitude": float(point["longs"])
        }]

    final_points = []

    for index in range(
        len(path) - 1
    ):

        start_vertex = path[index]
        end_vertex = path[index + 1]

        edge_points = _find_edge_polyline(
            start_vertex,
            end_vertex
        )

        if not edge_points:
            continue

        # Avoid duplicating the connecting point
        if final_points:

            last_point = final_points[-1]

            first_edge_point = edge_points[0]

            same_point = (
                abs(
                    last_point["latitude"]
                    - first_edge_point["latitude"]
                ) < 1e-8
                and
                abs(
                    last_point["longitude"]
                    - first_edge_point["longitude"]
                ) < 1e-8
            )

            if same_point:

                edge_points = edge_points[1:]

        final_points.extend(
            edge_points
        )

    # Re-number points cleanly
    for index, point in enumerate(
        final_points,
        start=1
    ):
        point["point"] = index

    return final_points


# ============================================================
# SELF ROUTE BUILDER
# ============================================================

def _get_self_route(
    origin,
    destination
):
    """
    Build a complete campus route:

        GPS origin
            ↓
        nearest graph vertex
            ↓
        shortest graph path
            ↓
        stored road polyline
            ↓
        waypoint list
    """

    start_vertex = _find_closest_vertex(
        origin
    )

    end_vertex = _find_closest_vertex(
        destination
    )

    if start_vertex is None:
        raise ValueError(
            "Could not resolve origin to campus graph"
        )

    if end_vertex is None:
        raise ValueError(
            "Could not resolve destination to campus graph"
        )

    path = _find_shortest_graph_path(
        start_vertex,
        end_vertex
    )

    if not path:
        raise ValueError(
            f"No campus route found from "
            f"{start_vertex} to {end_vertex}"
        )

    points = _graph_path_to_points(
        path
    )

    if not points:
        raise ValueError(
            f"Graph route found {path}, "
            f"but no polyline points were available"
        )

    return points


# ============================================================
# ROUTE BUILDING
# ============================================================

def _build_routes(
    kart_coords,
    marketplace_coords,
    delivery_point,
    routing_mode
):
    """
    Build pickup and delivery routes ONCE for a mission.

    routing_mode:
        1 -> self/campus route
        0 -> Google route

    Returns:
        receive_points,
        deliver_points,
        routing_source
    """

    state.last_error = None

    # ========================================================
    # SELF ROUTING
    # ========================================================

    if routing_mode == SELF_ROUTE:

        try:

            receive_points = _get_self_route(
                kart_coords,
                marketplace_coords
            )

            # Delivery starts from marketplace
            deliver_points = _get_self_route(
                marketplace_coords,
                delivery_point
            )

            return (
                receive_points,
                deliver_points,
                "self"
            )

        except Exception as error:

            state.last_error = (
                f"Self route error: {error}"
            )

            return (
                [],
                [],
                "self_failed"
            )

    # ========================================================
    # GOOGLE ROUTING
    # ========================================================

    receive_points = _get_google_points(
        kart_coords,
        marketplace_coords
    )

    deliver_points = _get_google_points(
        marketplace_coords,
        delivery_point
    )

    # ========================================================
    # GOOGLE FAILURE → CAMPUS FALLBACK
    # ========================================================

    if not receive_points:

        try:

            receive_points = _get_self_route(
                kart_coords,
                marketplace_coords
            )

            receive_source = True

        except Exception:

            receive_source = False

    else:

        receive_source = False

    if not deliver_points:

        try:

            deliver_points = _get_self_route(
                marketplace_coords,
                delivery_point
            )

            delivery_source = True

        except Exception:

            delivery_source = False

    else:

        delivery_source = False

    # ========================================================
    # Determine actual source
    # ========================================================

    if (
        receive_points
        and deliver_points
    ):

        if (
            receive_source
            or delivery_source
        ):
            return (
                receive_points,
                deliver_points,
                "google_with_self_fallback"
            )

        return (
            receive_points,
            deliver_points,
            "google"
        )

    state.last_error = (
        "Could not create a complete pickup "
        "and delivery route"
    )

    return (
        [],
        [],
        "route_failed"
    )


# ============================================================
# RESET PIPELINE
# ============================================================

def reset_pipeline():
    """
    Reset the current robot mission.

    Call this when:
        - a new order starts
        - old mission is cancelled
        - a completed mission must be restarted
    """

    global state

    with state_lock:

        state = PipelineState()


# ============================================================
# PIPELINE STATE FOR DASHBOARD / API
# ============================================================

def get_pipeline_state():
    """
    Return a safe snapshot of current navigation state.

    This will be useful later for the robot dashboard.
    """

    with state_lock:

        return {
            "active": state.active,
            "phase": state.phase,
            "routing_mode": state.routing_mode,
            "routing_source": state.routing_source,
            "receive_waypoint_index": (
                state.receive_waypoint_index
            ),
            "deliver_waypoint_index": (
                state.deliver_waypoint_index
            ),
            "receive_points_count": len(
                state.receive_points
            ),
            "deliver_points_count": len(
                state.deliver_points
            ),
            "last_command": state.last_command,
            "last_error": state.last_error,
        }


# ============================================================
# MAIN PIPELINE
# ============================================================

def pipeline(
    mp,
    k,
    dp,
    He,
    sd
):
    """
    Main autonomous decision pipeline.

    Parameters
    ----------
    mp:
        Marketplace coordinates.

    k:
        Current kart coordinates.

    dp:
        Delivery destination.

    He:
        Current kart heading.

    sd:
        Routing mode:
            1 -> self/campus graph
            0 -> Google route

    Returns
    -------
    str:
        One movement command:

            F
            SR
            SL
            R
            L
            STOP
    """

    global state

    # ========================================================
    # SAFETY: ACQUIRE CAMERA FRAME
    # ========================================================

    try:
        frame = get_frame()

    except Exception as error:

        with state_lock:
            state.last_error = (
                f"Camera frame error: {error}"
            )
            state.last_command = SAFE_STOP_COMMAND

        return SAFE_STOP_COMMAND

    # ========================================================
    # SAFETY: OBSTACLE DETECTION
    # ========================================================

    try:

        obstacle_result = movement(
            frame
        )

    except Exception as error:

        with state_lock:
            state.last_error = (
                f"Obstacle detector error: {error}"
            )
            state.last_command = SAFE_STOP_COMMAND

        return SAFE_STOP_COMMAND

    obstacle_present = _has_obstacle(
        obstacle_result.get(
            "obstacle_present",
            False
        )
    )

    # --------------------------------------------------------
    # IMPORTANT:
    # Obstacle safety has priority over navigation.
    # --------------------------------------------------------

    if obstacle_present:

        obstacle_command = _normalize_command(
            obstacle_result.get(
                "command",
                SAFE_STOP_COMMAND
            )
        )

        # Only allow known movement commands.
        allowed_commands = {
            "F",
            "SR",
            "SL",
            "R",
            "L",
            "STOP"
        }

        if obstacle_command not in allowed_commands:

            obstacle_command = SAFE_STOP_COMMAND

        with state_lock:
            state.last_command = (
                obstacle_command
            )

        return obstacle_command

    # ========================================================
    # VALIDATE ROUTING MODE
    # ========================================================

    try:

        routing_mode = int(sd)

    except (TypeError, ValueError):

        routing_mode = GOOGLE_ROUTE

    if routing_mode not in {
        SELF_ROUTE,
        GOOGLE_ROUTE
    }:

        routing_mode = GOOGLE_ROUTE

    # ========================================================
    # CREATE / DETECT CURRENT MISSION
    # ========================================================

    mission_key = _mission_key(
        mp,
        dp,
        routing_mode
    )

    with state_lock:

        should_initialize = (
            not state.active
            and state.phase != "COMPLETE"
        )

        mission_changed = (
            state.mission_key != mission_key
        )

        if mission_changed:

            should_initialize = True

    # ========================================================
    # INITIALIZE ROUTES
    # ========================================================

    if should_initialize:

        (
            receive_points,
            deliver_points,
            routing_source
        ) = _build_routes(
            kart_coords=k,
            marketplace_coords=mp,
            delivery_point=dp,
            routing_mode=routing_mode
        )

        if (
            not receive_points
            or not deliver_points
        ):

            with state_lock:

                state.active = False
                state.mission_key = mission_key
                state.routing_mode = routing_mode
                state.routing_source = routing_source
                state.phase = "IDLE"
                state.receive_points = []
                state.deliver_points = []
                state.receive_waypoint_index = 0
                state.deliver_waypoint_index = 0
                state.last_command = SAFE_STOP_COMMAND

                if not state.last_error:
                    state.last_error = (
                        "Route initialization failed"
                    )

            return SAFE_STOP_COMMAND

        # ----------------------------------------------------
        # Store new mission state
        # ----------------------------------------------------

        with state_lock:

            state.active = True

            state.mission_key = (
                mission_key
            )

            state.routing_mode = (
                routing_mode
            )

            state.routing_source = (
                routing_source
            )

            state.phase = "TO_PICKUP"

            state.receive_points = (
                receive_points
            )

            state.deliver_points = (
                deliver_points
            )

            state.receive_waypoint_index = 0
            state.deliver_waypoint_index = 0

            state.last_command = (
                SAFE_STOP_COMMAND
            )

            state.last_error = None

    # ========================================================
    # CURRENT PHASE SNAPSHOT
    # ========================================================

    with state_lock:

        phase = state.phase

        receive_points = list(
            state.receive_points
        )

        deliver_points = list(
            state.deliver_points
        )

        receive_index = (
            state.receive_waypoint_index
        )

        deliver_index = (
            state.deliver_waypoint_index
        )

    # ========================================================
    # COMPLETED MISSION
    # ========================================================

    if phase == "COMPLETE":

        with state_lock:
            state.last_command = (
                SAFE_STOP_COMMAND
            )

        return SAFE_STOP_COMMAND

    # ========================================================
    # PHASE 1:
    # KART → MARKETPLACE
    # ========================================================

    if phase == "TO_PICKUP":

        # ----------------------------------------------------
        # Direct destination arrival check
        # ----------------------------------------------------

        try:

            distance_to_marketplace = (
                calculate_distance(
                    to_tuple(k),
                    to_tuple(mp)
                )
            )

        except Exception as error:

            with state_lock:
                state.last_error = (
                    f"Pickup distance error: {error}"
                )
                state.last_command = (
                    SAFE_STOP_COMMAND
                )

            return SAFE_STOP_COMMAND

        # ----------------------------------------------------
        # Marketplace reached
        # ----------------------------------------------------

        if (
            distance_to_marketplace
            <= ARRIVAL_THRESHOLD
        ):

            with state_lock:

                # Automatically begin delivery phase
                # after reaching marketplace.
                state.phase = "TO_DELIVERY"

                # Reset delivery waypoint progress.
                state.deliver_waypoint_index = 0

                state.last_command = (
                    SAFE_STOP_COMMAND
                )

            # Return STOP for this cycle.
            # Next cycle starts delivery navigation.
            return SAFE_STOP_COMMAND

        # ----------------------------------------------------
        # Continue pickup route
        # ----------------------------------------------------

        navigation_result = navigate(
            heading=He,
            current_coords=k,
            points=receive_points,
            waypoint_index=receive_index
        )

        new_index = navigation_result.get(
            "waypoint_index",
            receive_index
        )

        command = _normalize_command(
            navigation_result.get(
                "command",
                SAFE_STOP_COMMAND
            )
        )

        route_complete = bool(
            navigation_result.get(
                "route_complete",
                False
            )
        )

        # ----------------------------------------------------
        # Route endpoint reached
        # ----------------------------------------------------

        if route_complete:

            with state_lock:

                state.phase = "TO_DELIVERY"

                state.receive_waypoint_index = (
                    new_index
                )

                state.deliver_waypoint_index = 0

                state.last_command = (
                    SAFE_STOP_COMMAND
                )

            return SAFE_STOP_COMMAND

        # ----------------------------------------------------
        # Save progress
        # ----------------------------------------------------

        with state_lock:

            state.receive_waypoint_index = (
                new_index
            )

            state.last_command = command

        return command

    # ========================================================
    # PHASE 2:
    # MARKETPLACE → DELIVERY
    # ========================================================

    if phase == "TO_DELIVERY":

        # ----------------------------------------------------
        # Direct destination arrival check
        # ----------------------------------------------------

        try:

            distance_to_delivery = (
                calculate_distance(
                    to_tuple(k),
                    to_tuple(dp)
                )
            )

        except Exception as error:

            with state_lock:
                state.last_error = (
                    f"Delivery distance error: {error}"
                )
                state.last_command = (
                    SAFE_STOP_COMMAND
                )

            return SAFE_STOP_COMMAND

        # ----------------------------------------------------
        # Delivery reached
        # ----------------------------------------------------

        if (
            distance_to_delivery
            <= ARRIVAL_THRESHOLD
        ):

            with state_lock:

                state.phase = "COMPLETE"

                state.active = True

                state.last_command = (
                    SAFE_STOP_COMMAND
                )

            return SAFE_STOP_COMMAND

        # ----------------------------------------------------
        # Continue delivery route
        # ----------------------------------------------------
        navigation_result = navigate(
            heading=He,
            current_coords=k,
            points=deliver_points,
            waypoint_index=deliver_index
        )
        new_index = navigation_result.get(
            "waypoint_index",
            deliver_index
        )
        command = _normalize_command(
            navigation_result.get(
                "command",
                SAFE_STOP_COMMAND
            )
        )
        route_complete = bool(
            navigation_result.get(
                "route_complete",
                False
            )
        )
        # ----------------------------------------------------
        # Route complete
        # ----------------------------------------------------
        if route_complete:
            with state_lock:
                state.phase = "COMPLETE"
                state.deliver_waypoint_index = (
                    new_index
                )
                state.last_command = (
                    SAFE_STOP_COMMAND
                )
            return SAFE_STOP_COMMAND
        # ----------------------------------------------------
        # Save progress
        # ----------------------------------------------------
        with state_lock:
            state.deliver_waypoint_index = (
                new_index
            )
            state.last_command = command
        return command
    # ========================================================
    # UNKNOWN STATE
    # ========================================================
    with state_lock:
        state.active = False
        state.phase = "IDLE"
        state.last_error = (
            f"Invalid pipeline phase: {phase}"
        )
        state.last_command = (
            SAFE_STOP_COMMAND
        )
    return SAFE_STOP_COMMAND
