const API_BASE_URL=(window.AUTO_DROP_API_URL||localStorage.getItem("autodrop_api_url")||"http://localhost:8000").replace(/\/$/,"");
const DEFAULT_MAP_CENTER=[24.435455,77.162249];
const state={kartId:sessionStorage.getItem("autodrop_kart_id")||"",currentPage:"navigation",navigationMode:"google",currentMission:null,maps:{kart:null,preview:null},previewMarkers:[],previewLine:null};
const dom=id=>document.getElementById(id);
function toast(message,type="normal"){const t=dom("toast");t.textContent=message;t.className=`toast ${type}`;t.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.hidden=true,3200)}
function errorBox(id,message){const b=dom(id);b.hidden=!message;b.textContent=message||""}
function coord(v){const n=Number(v);return Number.isFinite(n)?n.toFixed(6):"—"}
function history(){try{const x=JSON.parse(localStorage.getItem("autodrop_route_history")||"[]");return Array.isArray(x)?x:[]}catch{return[]}}
function saveHistory(x){const h=history();h.unshift(x);localStorage.setItem("autodrop_route_history",JSON.stringify(h.slice(0,12)))}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function date(v){try{return new Intl.DateTimeFormat(undefined,{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(v))}catch{return""}}
function identity(){const id=state.kartId||"—";dom("sidebar-kart-id").textContent=`Kart ${id}`;dom("topbar-kart-id").textContent=id;dom("management-kart-id").textContent=id;dom("profile-kart-id").textContent=id}
function apiStatus(ok,text){[dom("api-status-pill").querySelector(".status-dot"),dom("sidebar-status-dot"),dom("management-status-dot")].forEach(x=>x.className=`status-dot ${ok?"online":"offline"}`);dom("api-status-pill").querySelector("span:last-child").textContent=ok?"API Online":"API Offline";dom("sidebar-status-text").textContent=ok?"Connected":text;dom("management-status-text").textContent=ok?"API connected":"Telemetry pending";dom("connection-value").textContent=ok?"Connected":"Unavailable"}
async function api(path,opt={}){const r=await fetch(`${API_BASE_URL}${path}`,{...opt,headers:{"Content-Type":"application/json",...(opt.headers||{})}});let b=null;try{b=await r.json()}catch{}if(!r.ok){throw new Error(b?.detail||b?.message||"Request failed.")}return b}
async function login(id,password){const r=await api("/kart/auth",{method:"POST",body:JSON.stringify({kart_id:id,password})});if(!r?.authenticated)throw new Error("Authentication failed.");state.kartId=r.kart_id;sessionStorage.setItem("autodrop_kart_id",state.kartId)}
async function logout(){try{if(state.kartId)await api(`/kart/logout/${encodeURIComponent(state.kartId)}`,{method:"POST"})}catch{}sessionStorage.removeItem("autodrop_kart_id");state.kartId="";state.currentMission=null;dom("app-shell").hidden=true;dom("login-screen").hidden=false;dom("login-form").reset();toast("Logged out.")}
async function status(){if(!state.kartId){apiStatus(false,"Not authenticated");return}try{const r=await api(`/kart/status/${encodeURIComponent(state.kartId)}`);apiStatus(true,"Connected");if(r?.authenticated===false)showLogin()}catch{apiStatus(false,"API unavailable")}}
function showLogin(){dom("app-shell").hidden=true;dom("login-screen").hidden=false}
function showApp(){dom("login-screen").hidden=true;dom("app-shell").hidden=false;identity();maps();renderHistory();renderMission();page(state.currentPage);status()}
function page(p){state.currentPage=p;document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.page===p));document.querySelectorAll(".page").forEach(x=>x.classList.remove("active-page"));const s=dom(`page-${p}`);if(s)s.classList.add("active-page");const titles={navigation:"Navigation","create-route":"Create Route","kart-management":"Kart Management",profile:"Profile"};dom("page-title").textContent=titles[p]||"Navigation";setTimeout(()=>{state.maps.kart?.invalidateSize();state.maps.preview?.invalidateSize()},50)}
function maps(){if(!window.L)return;if(!state.maps.kart){state.maps.kart=L.map("kart-map",{zoomControl:false}).setView(DEFAULT_MAP_CENTER,17);L.control.zoom({position:"topright"}).addTo(state.maps.kart);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:20,attribution:"&copy; OpenStreetMap contributors"}).addTo(state.maps.kart)}if(!state.maps.preview){state.maps.preview=L.map("route-preview-map",{zoomControl:false}).setView(DEFAULT_MAP_CENTER,17);L.control.zoom({position:"topright"}).addTo(state.maps.preview);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:20,attribution:"&copy; OpenStreetMap contributors"}).addTo(state.maps.preview)}}
function markerIcon(color){return L.divIcon({className:"",html:`<div style="width:16px;height:16px;border-radius:50%;background:${color};border:3px solid #fff;box-shadow:0 2px 8px rgba(0,0,0,.24)"></div>`,iconSize:[16,16],iconAnchor:[8,8]})}
function preview(){if(!state.maps.preview)return;state.previewMarkers.forEach(m=>state.maps.preview.removeLayer(m));state.previewMarkers=[];if(state.previewLine){state.maps.preview.removeLayer(state.previewLine);state.previewLine=null}const a=[{lat:dom("user-lat").value,lng:dom("user-lng").value,label:dom("user-name").value||"User",color:"#2b7aff"},{lat:dom("delivery-lat").value,lng:dom("delivery-lng").value,label:dom("delivery-name").value||"Delivery",color:"#1bb77a"},{lat:dom("final-lat").value,lng:dom("final-lng").value,label:dom("final-name").value||"Final",color:"#7658f5"}];const pts=[];a.forEach(x=>{const lat=Number(x.lat),lng=Number(x.lng);if(Number.isFinite(lat)&&Number.isFinite(lng)){const m=L.marker([lat,lng],{icon:markerIcon(x.color)}).bindTooltip(x.label).addTo(state.maps.preview);state.previewMarkers.push(m);pts.push([lat,lng])}});if(pts.length>=2)state.previewLine=L.polyline(pts,{color:"#1769ff",weight:4,opacity:.78,dashArray:"8 8"}).addTo(state.maps.preview);if(pts.length)state.maps.preview.fitBounds(L.latLngBounds(pts),{padding:[30,30],maxZoom:17});else state.maps.preview.setView(DEFAULT_MAP_CENTER,17)}
function formMission(){const x={user:{latitude:Number(dom("user-lat").value),longitude:Number(dom("user-lng").value),name:dom("user-name").value.trim()},delivery:{latitude:Number(dom("delivery-lat").value),longitude:Number(dom("delivery-lng").value),name:dom("delivery-name").value.trim()},final:{latitude:Number(dom("final-lat").value),longitude:Number(dom("final-lng").value),name:dom("final-name").value.trim()}};for(const p of Object.values(x)){if(!Number.isFinite(p.latitude)||!Number.isFinite(p.longitude))throw new Error("Enter valid latitude and longitude for all three locations.");if(p.latitude<-90||p.latitude>90||p.longitude<-180||p.longitude>180)throw new Error("One or more coordinates are outside valid GPS ranges.")}return x}
async function send(mission,mode,manual=null){return api(`/kart/command/${encodeURIComponent(state.kartId)}`,{method:"POST",body:JSON.stringify({navigation_mode:mode,user_coords:{latitude:mission.user.latitude,longitude:mission.user.longitude},delivery_point:{latitude:mission.delivery.latitude,longitude:mission.delivery.longitude},final_location:{latitude:mission.final.latitude,longitude:mission.final.longitude},manual_command:manual})})}
function renderHistory(){const c=dom("route-history"),h=history();if(!h.length){c.innerHTML=`<div class="card" style="padding:24px;text-align:center"><strong style="font-size:12px">No previous routes</strong><div style="margin-top:5px;color:#93a0b0;font-size:10px">Routes created from this dashboard will appear here.</div></div>`;return}c.innerHTML=h.slice(0,8).map((x,i)=>{const mode=x.navigation_mode==="self"?"Self Route":x.navigation_mode==="manual"?"Manual":"Google Route";return `<div class="history-item"><div class="history-marker">${i+1}</div><div><strong>${esc(x.user.name||`${x.user.latitude.toFixed(4)}, ${x.user.longitude.toFixed(4)}`)} → ${esc(x.final.name||`${x.final.latitude.toFixed(4)}, ${x.final.longitude.toFixed(4)}`)}</strong><span>${date(x.created_at)} · ${mode}</span></div><div><span>${esc(x.delivery.name||"Delivery point")}</span></div><span class="history-status">Created</span></div>`}).join("")}
function renderMission(){const c=dom("current-route-chain"),m=state.currentMission;if(!m){dom("current-route-status").className="soft-chip neutral";dom("current-route-status").textContent="No route";c.innerHTML=`<div class="empty-state small"><div class="empty-icon">＋</div><strong>No active route</strong><span>Create a route to start navigation.</span></div>`;return}const mode=m.navigation_mode==="self"?"Self Route":m.navigation_mode==="manual"?"Manual":"Google Route";dom("current-route-status").className="soft-chip blue-chip";dom("current-route-status").textContent=mode;const items=[{n:"1",c:"blue",t:m.user.name||"User location",p:m.user,s:"Target"},{n:"2",c:"green",t:m.delivery.name||"Delivery point",p:m.delivery,s:"Next"},{n:"3",c:"purple",t:m.final.name||"Final destination",p:m.final,s:"Final"}];c.innerHTML=items.map(x=>`<div class="route-node"><div class="route-node-marker ${x.c}">${x.n}</div><div><strong>${esc(x.t)}</strong><span>${coord(x.p.latitude)}, ${coord(x.p.longitude)}</span></div><div class="route-node-status">${x.s}</div></div>`).join("")}
function modes(){document.querySelectorAll(".mode-card").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".mode-card").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");state.navigationMode=b.dataset.mode;dom("manual-controls").hidden=state.navigationMode!=="manual";dom("profile-mode").textContent=state.navigationMode}))}
async function startRoute(){errorBox("route-form-error","");let m;try{m=formMission()}catch(e){errorBox("route-form-error",e.message);return}try{await send(m,state.navigationMode,null);const record={id:(crypto.randomUUID?crypto.randomUUID():String(Date.now())),created_at:new Date().toISOString(),navigation_mode:state.navigationMode,user:m.user,delivery:m.delivery,final:m.final};state.currentMission=record;saveHistory(record);renderHistory();renderMission();toast("Route command sent successfully.","success");page("navigation")}catch(e){errorBox("route-form-error",e.message)}}
async function manual(cmd){if(!state.currentMission){toast("Create a mission before using manual control.","error");return}try{await send(state.currentMission,"manual",cmd);state.currentMission.navigation_mode="manual";dom("profile-mode").textContent="manual";renderMission();toast(`Manual command ${cmd} sent.`,cmd==="STOP"?"success":"normal")}catch(e){toast(e.message,"error")}}
function loginSetup(){dom("toggle-password").onclick=()=>{const i=dom("kart-password");i.type=i.type==="password"?"text":"password"};dom("login-form").addEventListener("submit",async e=>{e.preventDefault();errorBox("login-error","");const id=dom("kart-id").value.trim(),pw=dom("kart-password").value;if(!id||!pw){errorBox("login-error","Enter both Kart ID and password.");return}const b=e.submitter;b.disabled=true;const old=b.innerHTML;b.innerHTML="Authenticating…";try{await login(id,pw);showApp();toast(`Authenticated as ${state.kartId}.`,"success")}catch(x){errorBox("login-error",x.message)}finally{b.disabled=false;b.innerHTML=old}})}
function navSetup(){document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>page(b.dataset.page));dom("route-from-nav").onclick=()=>page("create-route");dom("create-route-cta").onclick=()=>page("create-route");dom("logout-button").onclick=logout;dom("clear-history").onclick=()=>{localStorage.removeItem("autodrop_route_history");renderHistory();toast("Route history cleared.")};dom("send-route-command").onclick=startRoute;document.querySelectorAll("[data-manual-command]").forEach(b=>b.onclick=()=>manual(b.dataset.manualCommand));dom("support-link").onclick=()=>{location.href="mailto:tiwariaatish24@gmail.com"}}
function serviceSetup(){dom("service-form").onsubmit=e=>{e.preventDefault();const type=dom("service-type").value,msg=dom("service-message").value.trim();if(!msg){toast("Describe the service issue first.","error");return}const subject=encodeURIComponent(`AutoDrop Service Request — ${state.kartId} — ${type}`),body=encodeURIComponent(["AutoDrop Service Request","",`Kart ID: ${state.kartId}`,`Issue Type: ${type}`,"",msg].join("\n"));location.href=`mailto:tiwariaatish24@gmail.com?subject=${subject}&body=${body}`;dom("service-form").reset()}}
function inputs(){["user-lat","user-lng","user-name","delivery-lat","delivery-lng","delivery-name","final-lat","final-lng","final-name"].forEach(id=>dom(id).addEventListener("input",preview))}
function boot(){loginSetup();navSetup();serviceSetup();modes();inputs();dom("profile-api-url").textContent=API_BASE_URL;setInterval(status,10000);state.kartId?showApp():showLogin()}
boot();